'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {CalendarDays,Check,Clock3,LogOut,RefreshCw,X} from 'lucide-react';
import {createSupabaseBrowserClient} from '@/lib/supabase/browser';
type Appointment={id:string;customer_name:string;customer_phone:string;starts_at:string;ends_at:string;status:'solicitada'|'confirmada'|'cancelada';salon_services:{name:string}|null};
export function AdminLogin({signOut=false}:{signOut?:boolean}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const client=createSupabaseBrowserClient();const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;window.location.reload()}catch(e){setError(e instanceof Error?e.message:'No fue posible iniciar sesión.')}finally{setBusy(false)}}
 const router=useRouter();
 async function logout(){const client=createSupabaseBrowserClient();await client.auth.signOut();router.refresh()}
 return <main className="admin-page"><section className="admin-card"><Link className="brand" href="/">Danny<span>SALÓN DE BELLEZA</span></Link><p className="eyebrow rose">PANEL PRIVADO</p><h1>{signOut?'No autorizado':'Agenda de citas'}</h1>{signOut?<button className="admin-secondary" onClick={logout}><LogOut size={16}/>Salir de esta cuenta</button>:<form className="admin-login" onSubmit={login}><label>Correo<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="admin-error">{error}</p>}<button className="button pink" disabled={busy}>{busy?'Ingresando…':'Entrar al panel'}</button></form>}<Link href="/" className="admin-back">Volver al sitio público</Link></section></main>
}
export function AdminDashboard({email,initialRows}:{email:string;initialRows:Appointment[]}){
 const [rows,setRows]=useState<Appointment[]>(initialRows),[loading,setLoading]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('todas');
 async function load(){setLoading(true);setError('');try{const client=createSupabaseBrowserClient();const {data,error}=await client.from('salon_appointments').select('id,customer_name,customer_phone,starts_at,ends_at,status,salon_services(name)').order('starts_at',{ascending:true});if(error)throw error;setRows((data||[]) as unknown as Appointment[])}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar las citas.')}finally{setLoading(false)}}
 async function changeStatus(id:string,status:Appointment['status']){const client=createSupabaseBrowserClient();const {error}=await client.from('salon_appointments').update({status}).eq('id',id);if(error){setError(error.message);return}await load()}
 const router=useRouter();
 async function logout(){const client=createSupabaseBrowserClient();await client.auth.signOut();router.refresh()}
 const visible=rows.filter(r=>filter==='todas'||r.status===filter), pending=rows.filter(r=>r.status==='solicitada').length;
 return <main className="admin-page admin-dashboard"><header className="admin-top"><div><Link className="brand" href="/">Danny<span>SALÓN DE BELLEZA</span></Link><p className="eyebrow rose">PANEL DE CITAS</p></div><button className="admin-secondary" onClick={logout}><LogOut size={16}/>Salir</button></header><section className="admin-welcome"><div><p className="eyebrow rose">HOLA, DANNY</p><h1>Tu agenda,<br/><em>en un solo lugar.</em></h1><p className="admin-intro">Sesión iniciada como {email}</p></div><div className="admin-count"><CalendarDays/><strong>{pending}</strong><span>{pending===1?'solicitud por revisar':'solicitudes por revisar'}</span></div></section><section className="admin-agenda"><div className="admin-agenda-head"><div><h2>Citas</h2><p>Solicitudes nuevas y próximas visitas</p></div><button className="admin-refresh" onClick={()=>void load()} aria-label="Actualizar"><RefreshCw size={17}/></button></div><nav className="admin-filters">{[['todas','Todas'],['solicitada','Solicitadas'],['confirmada','Confirmadas'],['cancelada','Canceladas']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</nav>{error&&<p className="admin-error">{error}</p>}{loading?<p className="admin-empty">Cargando agenda…</p>:visible.length===0?<p className="admin-empty">No hay citas en esta categoría todavía.</p>:<div className="appointment-list">{visible.map(a=>{const start=new Date(a.starts_at);return <article className="appointment-card" key={a.id}><div className="appointment-date"><strong>{new Intl.DateTimeFormat('es-CO',{day:'2-digit'}).format(start)}</strong><span>{new Intl.DateTimeFormat('es-CO',{month:'short'}).format(start)}</span></div><div className="appointment-main"><div className="appointment-title"><h3>{a.customer_name}</h3><span className={`status-pill status-${a.status}`}>{a.status}</span></div><p>{a.salon_services?.name||'Servicio'}</p><p className="appointment-meta"><Clock3 size={14}/>{new Intl.DateTimeFormat('es-CO',{weekday:'long',hour:'numeric',minute:'2-digit'}).format(start)}<span>·</span>{a.customer_phone}</p></div><div className="appointment-actions">{a.status==='solicitada'&&<button className="confirm-action" onClick={()=>void changeStatus(a.id,'confirmada')}><Check size={15}/>Confirmar</button>}{a.status!=='cancelada'&&<button className="cancel-action" onClick={()=>void changeStatus(a.id,'cancelada')}><X size={15}/>Cancelar</button>}</div></article>})}</div>}</section><p className="admin-private-note">Solo tú puedes ver y gestionar esta agenda.</p></main>
}
