'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,ChevronLeft,MessageCircle,Scissors,Sparkles,X,Send,Clock3} from 'lucide-react';
import {services} from '@/lib/salon';
type Step='home'|'info'|'service'|'date'|'time'|'details'|'done';
type Booking={service:string;date:string;time:string;name:string;phone:string};
const pad=(n:number)=>String(n).padStart(2,'0');
const dateKey=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const prettyDate=(s:string)=>new Intl.DateTimeFormat('es-CO',{weekday:'long',day:'numeric',month:'long'}).format(new Date(`${s}T12:00:00`));
export function BookingChat(){
 const [open,setOpen]=useState(false),[step,setStep]=useState<Step>('home'),[booking,setBooking]=useState<Booking>({service:'',date:'',time:'',name:'',phone:''}),[busy,setBusy]=useState(false),[busyAvailability,setBusyAvailability]=useState(false),[bookedSlots,setBookedSlots]=useState<string[]>([]),[demo,setDemo]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const openChat=()=>setOpen(true);window.addEventListener('salon:open-booking',openChat);return()=>window.removeEventListener('salon:open-booking',openChat)},[]);
 const update=(key:keyof Booking,value:string)=>setBooking(prev=>({...prev,[key]:value}));
 const reset=()=>{setStep('home');setNotice('');setDemo(false);setBooking({service:'',date:'',time:'',name:'',phone:''})};
 async function chooseDate(date:string){update('date',date);setBusyAvailability(true);try{const res=await fetch(`/api/bookings?date=${date}`);const data=await res.json() as {booked?:string[];demo?:boolean;error?:string};if(!res.ok)throw new Error(data.error);setBookedSlots(data.booked||[]);if(data.demo)setDemo(true);setStep('time')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos cargar los horarios.');}finally{setBusyAvailability(false)}}
 async function submit(){setBusy(true);setNotice('');try{const res=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(booking)});const data=await res.json() as {ok?:boolean;demo?:boolean;error?:string};if(!res.ok)throw new Error(data.error||'No pudimos registrar la solicitud.');setDemo(Boolean(data.demo));setStep('done')}catch(e){setNotice(e instanceof Error?e.message:'Intenta de nuevo en un momento.')}finally{setBusy(false)}}
 const dates=Array.from({length:21},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i+1);return d});
 return <div className="booking-widget" id="agenda-chat"><button className="booking-launcher" onClick={()=>setOpen(!open)} aria-label={open?'Cerrar asistente de citas':'Abrir asistente de citas'}>{open?<X size={21}/>:<MessageCircle size={21}/>}<span>{open?'Cerrar':'Agenda tu cita'}</span></button>{open&&<section className="booking-chat" aria-label="Asistente de citas">
  <header className="chat-head"><span className="chat-mark"><Sparkles size={17}/></span><div><strong>Hola, bienvenida</strong><small>Asistente de Salón Danny</small></div><button onClick={()=>setOpen(false)} aria-label="Cerrar chat"><X size={19}/></button></header>
  <div className="chat-content"><p className="chat-bubble">¿Cómo te ayudamos hoy?</p>
   {step==='home'&&<div className="chat-options"><button onClick={()=>setStep('service')}><CalendarDays/>Quiero reservar una cita</button><button onClick={()=>setStep('info')}><Scissors/>Servicios y precios</button><button onClick={()=>setNotice('El horario informado es de 8:00 a. m. a 9:00 p. m. La dirección es Calle 76 Sur n.º 16P-43.')}><Clock3/>Horarios y ubicación</button><button onClick={()=>setNotice('Para hablar con Danny por WhatsApp, escribe al 350 530 9936.')}><MessageCircle/>Hablar con Danny</button></div>}
   {step==='info'&&<><p className="chat-prompt">Danny ofrece manicure, pedicure, uñas semipermanentes, acrílico, poligel, press-on, dipping, cejas, pestañas punto a punto, keratina, alisados, peinados y trenzas (también para niñas), corte dama, repolarización, limpieza facial y depilación con cera.</p><p className="chat-footnote">Las uñas tienen precios fijos. Keratinas y peinados se cotizan según el largo y la cantidad de cabello. Pregunta a Danny por el precio de cada servicio y los productos disponibles.</p><button className="chat-submit" onClick={()=>setStep('service')}>Elegir un servicio para reservar</button><button className="chat-back" onClick={()=>setStep('home')}><ChevronLeft/>Volver al menú</button></>}
   {step==='service'&&<><p className="chat-prompt">¿Qué servicio te gustaría reservar?</p><div className="chat-service-list">{services.map(s=><button key={s.slug} className={booking.service===s.slug?'chosen':''} onClick={()=>{update('service',s.slug);setStep('date')}}>{s.name}<span>60 min</span></button>)}</div><button className="chat-back" onClick={()=>setStep('home')}><ChevronLeft/>Volver</button></>}
   {step==='date'&&<><p className="chat-prompt">Elige un día para tu cita</p><div className="chat-dates">{dates.map(d=><button key={dateKey(d)} disabled={busyAvailability} className={booking.date===dateKey(d)?'chosen':''} onClick={()=>chooseDate(dateKey(d))}><small>{new Intl.DateTimeFormat('es-CO',{weekday:'short'}).format(d)}</small><strong>{d.getDate()}</strong><small>{new Intl.DateTimeFormat('es-CO',{month:'short'}).format(d)}</small></button>)}</div><p className="chat-footnote">Horario del salón: 8:00 a. m. – 9:00 p. m.</p><button className="chat-back" onClick={()=>setStep('service')}><ChevronLeft/>Cambiar servicio</button></>}
   {step==='time'&&<><p className="chat-prompt">Horarios disponibles para el {prettyDate(booking.date)}</p><div className="chat-times">{Array.from({length:13},(_,i)=>i+8).map(h=>{const slot=`${pad(h)}:00`,taken=bookedSlots.includes(slot);return <button key={h} disabled={taken} className={`${booking.time===slot?'chosen':''} ${taken?'slot-taken':''}`} onClick={()=>{update('time',slot);setStep('details')}}>{h>12?`${h-12}:00 p. m.`:h===12?'12:00 p. m.':`${h}:00 a. m.`}{taken?' · Ocupado':''}</button>})}</div><p className="chat-footnote">La cita dura 1 hora. El horario se confirmará al guardar la agenda.</p><button className="chat-back" onClick={()=>setStep('date')}><ChevronLeft/>Cambiar fecha</button></>}
   {step==='details'&&<><p className="chat-prompt">Déjanos tus datos para solicitar la cita</p><div className="booking-fields"><label>Tu nombre<input value={booking.name} onChange={e=>update('name',e.target.value)} autoComplete="name" placeholder="Nombre y apellido"/></label><label>Teléfono<input value={booking.phone} onChange={e=>update('phone',e.target.value)} inputMode="tel" autoComplete="tel" placeholder="Tu número de contacto"/></label></div><div className="booking-summary">{services.find(s=>s.slug===booking.service)?.name} · {prettyDate(booking.date)} · {booking.time}</div><button className="chat-submit" disabled={busy||!booking.name.trim()||booking.phone.replace(/\D/g,'').length<7} onClick={submit}>{busy?'Enviando…':<>Solicitar cita <Send size={16}/></>}</button><button className="chat-back" onClick={()=>setStep('time')}><ChevronLeft/>Cambiar horario</button></>}
   {step==='done'&&<div className="chat-done"><Sparkles/><h3>{demo?'Vista de prueba':'¡Gracias, '+booking.name.split(' ')[0]+'!'}</h3><p>{demo?'La reserva no se guardó todavía. Conecta Supabase para activar la agenda.':<>Tu solicitud para {prettyDate(booking.date)} a las {booking.time} quedó enviada a Dani. Ella podrá confirmarla desde su panel.</>}</p><button className="chat-submit" onClick={reset}>Volver al inicio</button></div>}
   {notice&&step!=='done'&&<div className="chat-notice">{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar mensaje"><X size={14}/></button></div>}
  </div><footer className="chat-footer">Tus datos se usan únicamente para gestionar tu cita.</footer>
 </section>}</div>
}
