'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Menu,Pause,Play,Plus,Sparkles,X,ChevronLeft,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Smoke} from './smoke';
import {Typewriter,ParticleHalo,useGalleryMotion} from './visual-effects';
import {services} from '@/lib/salon';
import {contact} from '@/lib/salon';
import {BookingChat} from './booking-chat';
type Service=typeof services[number];
const gallery=[{image:'nails',title:'Pink obsession',text:'Fucsia, negro y destellos. Una propuesta de nail art con personalidad.',position:'center'},{image:'beauty',title:'Black velvet',text:'Cabello oscuro, movimiento suave y una mirada protagonista.',position:'center 25%'},{image:'nails',title:'Detalles que brillan',text:'Una mirada de cerca a los contrastes y los acabados joya.',position:'80% center'}];
export function Salon({service}:{service?:Service}){
 const [menu,setMenu]=useState(false),[paused,setPaused]=useState(false),[selected,setSelected]=useState<number|null>(null);const track=useRef<HTMLDivElement>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setPaused(media.matches);const update=()=>setPaused(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{document.documentElement.classList.toggle('motion-paused',paused);return()=>document.documentElement.classList.remove('motion-paused')},[paused]);
 useEffect(()=>{const els=document.querySelectorAll('.reveal');els.forEach(e=>e.classList.add('reveal-ready'));const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[service]);
 useGalleryMotion(paused,service);
 useEffect(()=>{if(paused)return;const update=()=>document.documentElement.style.setProperty('--scroll',String(Math.min(scrollY,900)));addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update)},[paused]);
 const nav=()=>setMenu(false);
 return <><Smoke paused={paused}/><div className="ambient" aria-hidden="true"/><a className="skip" href="#contenido">Saltar al contenido</a>
 <header className="header"><Link className="brand" href="/" aria-label="Danny, inicio">Danny<span>SALÓN DE BELLEZA</span></Link><nav aria-label="Navegación principal" className={menu?'nav open':'nav'}><Link onClick={nav} href="/#servicios">Servicios</Link><Link onClick={nav} href="/#inspiracion">Inspiración</Link><Link onClick={nav} href="/#esencia">El universo Danny</Link></nav><div className="header-actions"><button className="motion-button" aria-label={paused?'Activar animaciones':'Pausar animaciones'} onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}<span>{paused?'Activar':'Pausar'} movimiento</span></button><button className="menu-button" aria-label={menu?'Cerrar menú':'Abrir menú'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="contenido">{service?<>
 <section className="service-hero wrap"><div className="service-copy"><Link className="eyebrow back" href="/#servicios">Todos los servicios</Link><p className="eyebrow rose">{service.category}</p><h1>{service.name}<em>{service.line}</em></h1><p className="lead">{service.intro}</p><button className="button pink" onClick={()=>window.dispatchEvent(new Event('salon:open-booking'))}>Solicitar una cita</button></div><div className="service-photo"><img src={`/images/${service.image}.webp`} alt={service.image==='nails'?'Inspiración de manicure rosa y negro':'Inspiración de cabello largo y oscuro'}/><span className="image-caption">IMAGEN DE INSPIRACIÓN</span></div></section>
 <section id="detalles" className="wrap details"><p className="eyebrow rose">PENSADO PARA TI</p><h2 className="reveal">Cada look empieza<br/>con una <em>conversación.</em></h2><div className="detail-grid">{service.details.map(([title,body])=><article className="reveal" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="wrap other-services"><p className="eyebrow">SIGUE EXPLORANDO</p><h2>Completa tu <em>estilo.</em></h2><div className="other-links">{services.filter(s=>s.slug!==service.slug).map(s=><Link href={`/servicios/${s.slug}`} key={s.slug}>{s.name}<Plus size={18}/></Link>)}</div></section>
 </>:<>
 <section className="hero"><div className="hero-copy"><p className="eyebrow hero-overline"><span/> BEAUTY IS AN ATTITUDE</p><h1>Tu esencia.<br/>Tu estilo.<br/><em><Typewriter paused={paused}/></em></h1><p className="hero-description">Uñas y cabello con personalidad.<br/>Bienvenida al universo de Danny.</p><div className="hero-buttons"><a className="button pink sparkle-button" href="#servicios">Descubre los servicios<span className="corner-glint" aria-hidden="true">✦</span></a><a className="text-link" href="#inspiracion">Encuentra tu inspiración</a></div></div><div className="hero-art"><div className="diamond-halo" aria-hidden="true"/><div className="diamond-top"><img className="diamond" src="/images/diamond-transparent.png" alt=""/></div><ParticleHalo paused={paused}/><span className="orbit-label">UN BRILLO QUE ES SOLO TUYO</span></div><div className="hero-bottom"><span>MANICURE · CABELLO · BELLEZA</span><span className="scroll-cue">DESLIZA PARA DESCUBRIR <i/></span><span>ESTILO SIN LÍMITES</span></div></section>
 <section id="servicios" className="wrap services"><div className="section-top reveal"><div><p className="eyebrow rose">NUESTROS SERVICIOS</p><h2>El detalle lo<br/>cambia <em>todo.</em></h2></div><p>Un color, una forma, un nuevo comienzo.<br/>Elige cómo quieres expresarte.</p></div><div className="service-grid"><Link href="/servicios/manicure" className="nail-feature reveal"><img src="/images/nails.webp" alt="Inspiración de uñas fucsia y negro con detalles brillantes" loading="lazy"/><div className="feature-top"><span>NUESTRA ESPECIALIDAD</span><Sparkles size={21}/></div><div className="feature-bottom"><h3>Manicure</h3><p>Pequeñas obras de arte.<br/>Toda tu personalidad.</p><span className="round-plus"><Plus/></span></div></Link><div className="service-list">{services.slice(1).map(s=><Link className="service-row reveal" key={s.slug} href={`/servicios/${s.slug}`}><div><h3>{s.name}</h3><p>{s.line}</p></div><Plus size={23}/></Link>)}</div></div></section>
 <section className="beauty-section" id="esencia"><div className="beauty-image"><img src="/images/beauty.webp" alt="Retrato editorial de belleza con cabello oscuro y luz rosa" loading="lazy"/></div><div className="beauty-copy reveal"><p className="eyebrow rose">EL UNIVERSO DANNY</p><h2>No se trata solo<br/>de un look.<br/><em>Se trata de ti.</em></h2><p>De tus uñas favoritas, del peinado que imaginas y de los detalles que hacen que te reconozcas frente al espejo.</p><p className="beauty-signature">Dale espacio a un cambio que te encante.</p><button className="button outline" onClick={()=>window.dispatchEvent(new Event('salon:open-booking'))}>Agenda tu cita</button></div></section>
 <section id="inspiracion" className={`gallery-stage ${paused?'no-pin':''}`}><div className="gallery-sticky"><div className="section-top wrap"><div><p className="eyebrow rose">GALERÍA</p><h2 className="gallery-heading">Un poco de <em><Typewriter paused={paused} variant="gallery"/></em></h2></div><div className="gallery-intro"><p>Colores, texturas y brillo para inspirarte.</p></div></div><div className="gallery-window"><div className="gallery-track" ref={track}>{gallery.map((g,i)=><button key={g.title} className={`gallery-item gallery-${i}`} onClick={()=>setSelected(i)} aria-label={`Ampliar ${g.title}`}><img src={`/images/${g.image}.webp`} alt={g.title} style={{objectPosition:g.position}} loading="lazy"/><div><h3>{g.title}</h3><span className="round-plus"><Plus/></span></div></button>)}</div></div></div></section>
 <section className="closing wrap reveal"><img src="/images/diamond-transparent.png" alt="" aria-hidden="true" loading="lazy"/><p className="eyebrow rose">SALÓN DE BELLEZA DANNY</p><h2>Hay muchas formas<br/>de brillar.<br/><em>Encuentra la tuya.</em></h2><a className="button pink" href="#servicios">Elige tu próximo look</a></section>
 </>}</main>
 <section className="location-section"><div className="location-grid wrap"><div className="location-copy"><p className="eyebrow rose">VISÍTANOS</p><h2>Tu próxima cita<br/><em>te espera aquí.</em></h2><p className="location-address">{contact.address}<br/>{contact.city}</p><a className="button pink" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(contact.mapsQuery)}`} target="_blank" rel="noreferrer">Abrir ubicación</a><a className="location-phone" href={`https://wa.me/${contact.whatsapp}`} target="_blank" rel="noreferrer">WhatsApp · {contact.phoneDisplay}</a></div><div className="map-frame"><iframe title="Mapa de ubicación de Salón de Belleza Danny" loading="lazy" src={`https://maps.google.com/maps?q=${encodeURIComponent(contact.mapsQuery)}&output=embed`}/><span className="map-caption">{contact.address} · {contact.city}</span></div></div></section>
 <footer className="footer wrap"><Link className="brand" href="/">Danny<span>SALÓN DE BELLEZA</span></Link><div><p>Manos que crean. Estilos que expresan.</p><span>Uñas · Peinados · Cuidado personal</span></div><a href="#contenido" className="text-link">Volver al inicio</a><p className="footer-note">Salón de Belleza Danny · Tu esencia, tu estilo, tu brillo.</p></footer>
 <BookingChat/>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent showCloseButton={false} className="gallery-dialog">{selected!==null&&<><DialogClose className="dialog-close" aria-label="Cerrar imagen"><X/></DialogClose><img className="dialog-image" src={`/images/${gallery[selected].image}.webp`} alt={gallery[selected].title}/><div className="dialog-text"><DialogTitle>{gallery[selected].title}</DialogTitle><DialogDescription>{gallery[selected].text}</DialogDescription><div className="dialog-controls"><button aria-label="Imagen anterior" onClick={()=>setSelected((selected+gallery.length-1)%gallery.length)}><ChevronLeft/></button><span>{selected+1} / {gallery.length}</span><button aria-label="Imagen siguiente" onClick={()=>setSelected((selected+1)%gallery.length)}><ChevronRight/></button></div></div></>}</DialogContent></Dialog></>;
}
