'use client';
import {useEffect,useRef,useState} from 'react';
const typewriterWords={
 hero:['Tu brillo.','Tu actitud.','Tu esencia.'],
 gallery:['color.','textura.','brillo.'],
 beauty:['Se trata de ti.','Tu esencia.','Tu estilo.'],
} as const;
type TypewriterVariant=keyof typeof typewriterWords;
export function Typewriter({variant='hero'}:{variant?:TypewriterVariant}){const words=typewriterWords[variant];const [text,setText]=useState<string>(words[0]);useEffect(()=>{let word=0,count=words[0].length,deleting=true,handle:ReturnType<typeof setTimeout>;function tick(){const phrase=words[word];if(deleting){count--;setText(phrase.slice(0,Math.max(0,count)));if(count<=0){deleting=false;word=(word+1)%words.length;handle=setTimeout(tick,320)}else handle=setTimeout(tick,55)}else{count++;setText(words[word].slice(0,count));if(count>=words[word].length){deleting=true;handle=setTimeout(tick,2300)}else handle=setTimeout(tick,100)}}handle=setTimeout(tick,2500);return()=>clearTimeout(handle)},[words]);return <><span className="sr-only">{words.join(' ')}</span><span aria-hidden="true" className={`typewriter typewriter-${variant}`}>{text}<i/></span></>}
export function ParticleHalo(){
 const ref=useRef<HTMLCanvasElement>(null),pointer=useRef({x:0,y:0});
 useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let frame=0,last=0,t=0;const resize=()=>{c.width=Math.round(c.clientWidth*Math.min(devicePixelRatio,1.5));c.height=Math.round(c.clientHeight*Math.min(devicePixelRatio,1.5))};resize();const observer=new ResizeObserver(resize);observer.observe(c);function draw(now:number){if(!document.hidden&&now-last>30){t+=.025*(1+Math.abs(pointer.current.x));const w=c!.width,h=c!.height;ctx!.clearRect(0,0,w,h);ctx!.globalCompositeOperation='lighter';for(let i=0;i<210;i++){const angle=i*2.399+t,level=(i/210-.5)*2,radius=w*.39*(.76+.17*Math.sin(level*4+t)),z=Math.cos(angle),x=Math.sin(angle)*radius,y=level*h*.38,tilt=pointer.current.x*.25,xx=w*.5+x+y*tilt,yy=h*.5+y+z*h*.09+pointer.current.y*x*.2,alpha=.24+(z+1)*.28;ctx!.fillStyle=`rgba(255,${Math.round(90+(z+1)*55)},200,${alpha})`;ctx!.beginPath();ctx!.arc(xx,yy,(1.1+(z+1)*1.1)*w/600,0,Math.PI*2);ctx!.fill()}last=now}frame=requestAnimationFrame(draw)}draw(100);return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[]);
 return <div className="particle-interaction" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();pointer.current.x=(e.clientX-r.left)/r.width-.5;pointer.current.y=(e.clientY-r.top)/r.height-.5}} onPointerLeave={()=>{pointer.current={x:0,y:0}}}><canvas ref={ref} aria-hidden="true"/></div>
}
export function useGalleryMotion(dependency:unknown){useEffect(()=>{const stage=document.querySelector<HTMLElement>('.gallery-stage'),rail=document.querySelector<HTMLElement>('.gallery-track'),win=document.querySelector<HTMLElement>('.gallery-window');if(!stage||!rail||!win)return;const cards=Array.from(rail.querySelectorAll<HTMLElement>('.gallery-item'));let frame=0,previous=scrollY,previousX=win.scrollLeft,velocity=0,scrollVelocity=0,last=0;function animate(now:number){if(now-last>16){const delta=scrollY-previous,dx=win!.scrollLeft-previousX;previous=scrollY;previousX=win!.scrollLeft;scrollVelocity+=(delta+dx-scrollVelocity)*.14;velocity+=(scrollVelocity-velocity)*.13;const mobile=innerWidth<=900;const progress=Math.max(0,Math.min(1,-stage!.getBoundingClientRect().top/Math.max(1,stage!.offsetHeight-innerHeight)));if(!mobile)rail!.style.transform=`translateX(${-progress*Math.max(0,rail!.scrollWidth-innerWidth+100)}px)`;cards.forEach((card,i)=>{const rect=card.getBoundingClientRect();const offset=Math.max(-1,Math.min(1,(rect.left+rect.width/2-innerWidth/2)/innerWidth));const wave=Math.sin(i*1.4+progress*5)*Math.min(70,Math.abs(velocity)*7);card.style.transform=`perspective(1100px) translateY(${wave}px) rotateY(${-offset*27}deg) rotateZ(${Math.max(-7,Math.min(7,velocity*.5))*Math.sin(i+1)}deg) scale(${1-Math.abs(offset)*.1})`});last=now}frame=requestAnimationFrame(animate)}frame=requestAnimationFrame(animate);return()=>{cancelAnimationFrame(frame);rail.style.transform='';cards.forEach(c=>c.style.transform='')}},[dependency])}
